# -*- coding: utf-8 -*-
"""notebook-scraping-sentiment-analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13zcMnZj9DIhN-4VItadjfMM1jGhkC34y

# **Notebook Scraping Proyek Sentimen Analisis**

- **Nama:** Fatikha Hudi Aryani
- **Email:** fatikhahudiaryani621@gmail.com
- **ID Dicoding:** fatikha_hudi_aryani
"""

!pip install google-play-scraper

# Import Library
from google_play_scraper import reviews_all, reviews, Sort
import pandas as pd

# Melakukan scraping untuk mengambil 30000 ulasan aplikasi tokopedia
scrap_review = reviews(
    'id.co.bri.brimo',
    lang='id',
    country='id',
    count = 10000
)

# Menyimpan hasil scrap ke dalam bentuk file csv
df = pd.DataFrame(scrap_review[0])
df.to_csv('brimo_reviews_10K.csv', index=False)
